=== willmurphyscode/dead-simple-weather/test/fixtures/files/json_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "city": {
            "id": "/properties/city",
            "properties": {
                "coord": {
                    "id": "/properties/city/properties/coord",
                    "properties": {
                        "lat": {
                            "id": "/properties/city/properties/coord/properties/lat",
                            "type": "number"
                        },
                        "lon": {
                            "id": "/properties/city/properties/coord/properties/lon",
                            "type": "number"
                        }
                    },
                    "type": "object"
                },
                "country": {
                    "id": "/properties/city/properties/country",
                    "type": "string"
                },
                "id": {
                    "id": "/properties/city/properties/id",
                    "type": "integer"
                },
                "name": {
                    "id": "/properties/city/properties/name",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "cnt": {
            "id": "/properties/cnt",
            "type": "integer"
        },
        "cod": {
            "id": "/properties/cod",
            "type": "string"
        },
        "list": {
            "id": "/properties/list",
            "items": {
                "id": "/properties/list/items",
                "properties": {
                    "clouds": {
                        "id": "/properties/list/items/properties/clouds",
                        "properties": {
                            "all": {
                                "id": "/properties/list/items/properties/clouds/properties/all",
                                "type": "integer"
                            }
                        },
                        "type": "object"
                    },
                    "dt": {
                        "id": "/properties/list/items/properties/dt",
                        "type": "integer"
                    },
                    "dt_txt": {
                        "id": "/properties/list/items/properties/dt_txt",
                        "type": "string"
                    },
                    "main": {
                        "id": "/properties/list/items/properties/main",
                        "properties": {
                            "grnd_level": {
                                "id": "/properties/list/items/properties/main/properties/grnd_level",
                                "type": "number"
                            },
                            "humidity": {
                                "id": "/properties/list/items/properties/main/properties/humidity",
                                "type": "integer"
                            },
                            "pressure": {
                                "id": "/properties/list/items/properties/main/properties/pressure",
                                "type": "number"
                            },
                            "sea_level": {
                                "id": "/properties/list/items/properties/main/properties/sea_level",
                                "type": "number"
                            },
                            "temp": {
                                "id": "/properties/list/items/properties/main/properties/temp",
                                "type": "number"
                            },
                            "temp_kf": {
                                "id": "/properties/list/items/properties/main/properties/temp_kf",
                                "type": "number"
                            },
                            "temp_max": {
                                "id": "/properties/list/items/properties/main/properties/temp_max",
                                "type": "number"
                            },
                            "temp_min": {
                                "id": "/properties/list/items/properties/main/properties/temp_min",
                                "type": "number"
                            }
                        },
                        "type": "object"
                    },
                    "sys": {
                        "id": "/properties/list/items/properties/sys",
                        "properties": {
                            "pod": {
                                "id": "/properties/list/items/properties/sys/properties/pod",
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "weather": {
                        "id": "/properties/list/items/properties/weather",
                        "items": {
                            "id": "/properties/list/items/properties/weather/items",
                            "properties": {
                                "description": {
                                    "id": "/properties/list/items/properties/weather/items/properties/description",
                                    "type": "string"
                                },
                                "icon": {
                                    "id": "/properties/list/items/properties/weather/items/properties/icon",
                                    "type": "string"
                                },
                                "id": {
                                    "id": "/properties/list/items/properties/weather/items/properties/id",
                                    "type": "integer"
                                },
                                "main": {
                                    "id": "/properties/list/items/properties/weather/items/properties/main",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "type": "array"
                    },
                    "wind": {
                        "id": "/properties/list/items/properties/wind",
                        "properties": {
                            "deg": {
                                "id": "/properties/list/items/properties/wind/properties/deg",
                                "type": "number"
                            },
                            "speed": {
                                "id": "/properties/list/items/properties/wind/properties/speed",
                                "type": "number"
                            }
                        },
                        "type": "object"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "message": {
            "id": "/properties/message",
            "type": "number"
        }
    },
    "type": "object"
}

=== willmurphyscode/dead-simple-weather/test/fixtures/files/open_weather_response.json
{
  "cod": "200",
  "message": 0.007,
  "cnt": 40,
  "list": [
    {
      "dt": 1493478000,
      "main": {
        "temp": 83.93,
        "temp_min": 83.32,
        "temp_max": 83.93,
        "pressure": 1025.66,
        "sea_level": 1032.1,
        "grnd_level": 1025.66,
        "humidity": 49,
        "temp_kf": 0.33
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "clouds": {
        "all": 12
      },
      "wind": {
        "speed": 8.03,
        "deg": 243.503
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-29 15:00:00"
    },
    {
      "dt": 1493488800,
      "main": {
        "temp": 87.84,
        "temp_min": 87.4,
        "temp_max": 87.84,
        "pressure": 1024.06,
        "sea_level": 1030.47,
        "grnd_level": 1024.06,
        "humidity": 44,
        "temp_kf": 0.25
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "02d"
        }
      ],
      "clouds": {
        "all": 8
      },
      "wind": {
        "speed": 8.28,
        "deg": 237.503
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-29 18:00:00"
    },
    {
      "dt": 1493499600,
      "main": {
        "temp": 88.39,
        "temp_min": 88.09,
        "temp_max": 88.39,
        "pressure": 1022.72,
        "sea_level": 1029.1,
        "grnd_level": 1022.72,
        "humidity": 41,
        "temp_kf": 0.17
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 48
      },
      "wind": {
        "speed": 8.84,
        "deg": 236.009
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-29 21:00:00"
    },
    {
      "dt": 1493510400,
      "main": {
        "temp": 83.82,
        "temp_min": 83.68,
        "temp_max": 83.82,
        "pressure": 1022.75,
        "sea_level": 1029.12,
        "grnd_level": 1022.75,
        "humidity": 44,
        "temp_kf": 0.08
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 7.38,
        "deg": 217.012
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-04-30 00:00:00"
    },
    {
      "dt": 1493521200,
      "main": {
        "temp": 81.28,
        "temp_min": 81.28,
        "temp_max": 81.28,
        "pressure": 1023.93,
        "sea_level": 1030.47,
        "grnd_level": 1023.93,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "clouds": {
        "all": 12
      },
      "wind": {
        "speed": 10.42,
        "deg": 213.501
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-04-30 03:00:00"
    },
    {
      "dt": 1493532000,
      "main": {
        "temp": 79.87,
        "temp_min": 79.87,
        "temp_max": 79.87,
        "pressure": 1023.43,
        "sea_level": 1029.96,
        "grnd_level": 1023.43,
        "humidity": 57,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 10.56,
        "deg": 220.501
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-04-30 06:00:00"
    },
    {
      "dt": 1493542800,
      "main": {
        "temp": 78.11,
        "temp_min": 78.11,
        "temp_max": 78.11,
        "pressure": 1024.32,
        "sea_level": 1030.89,
        "grnd_level": 1024.32,
        "humidity": 61,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 8.75,
        "deg": 227.001
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-04-30 09:00:00"
    },
    {
      "dt": 1493553600,
      "main": {
        "temp": 78.49,
        "temp_min": 78.49,
        "temp_max": 78.49,
        "pressure": 1026.2,
        "sea_level": 1032.72,
        "grnd_level": 1026.2,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 5.17,
        "deg": 237.002
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-30 12:00:00"
    },
    {
      "dt": 1493564400,
      "main": {
        "temp": 83.78,
        "temp_min": 83.78,
        "temp_max": 83.78,
        "pressure": 1025.92,
        "sea_level": 1032.46,
        "grnd_level": 1025.92,
        "humidity": 52,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "clouds": {
        "all": 12
      },
      "wind": {
        "speed": 6.17,
        "deg": 214.003
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-30 15:00:00"
    },
    {
      "dt": 1493575200,
      "main": {
        "temp": 87.16,
        "temp_min": 87.16,
        "temp_max": 87.16,
        "pressure": 1023.88,
        "sea_level": 1030.5,
        "grnd_level": 1023.88,
        "humidity": 44,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "02d"
        }
      ],
      "clouds": {
        "all": 8
      },
      "wind": {
        "speed": 8.52,
        "deg": 202.5
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-30 18:00:00"
    },
    {
      "dt": 1493586000,
      "main": {
        "temp": 86.64,
        "temp_min": 86.64,
        "temp_max": 86.64,
        "pressure": 1021.77,
        "sea_level": 1028.23,
        "grnd_level": 1021.77,
        "humidity": 40,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 11.23,
        "deg": 195.003
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2017-04-30 21:00:00"
    },
    {
      "dt": 1493596800,
      "main": {
        "temp": 81.5,
        "temp_min": 81.5,
        "temp_max": 81.5,
        "pressure": 1021.68,
        "sea_level": 1028.21,
        "grnd_level": 1021.68,
        "humidity": 43,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 11.65,
        "deg": 201.504
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-05-01 00:00:00"
    },
    {
      "dt": 1493607600,
      "main": {
        "temp": 78.75,
        "temp_min": 78.75,
        "temp_max": 78.75,
        "pressure": 1022.18,
        "sea_level": 1028.63,
        "grnd_level": 1022.18,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 11.1,
        "deg": 202.504
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-05-01 03:00:00"
    },
    {
      "dt": 1493618400,
      "main": {
        "temp": 77.1,
        "temp_min": 77.1,
        "temp_max": 77.1,
        "pressure": 1020.48,
        "sea_level": 1027.04,
        "grnd_level": 1020.48,
        "humidity": 58,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "clouds": {
        "all": 20
      },
      "wind": {
        "speed": 11.68,
        "deg": 201.003
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-05-01 06:00:00"
    },
    {
      "dt": 1493629200,
      "main": {
        "temp": 75.03,
        "temp_min": 75.03,
        "temp_max": 75.03,
        "pressure": 1019.47,
        "sea_level": 1025.95,
        "grnd_level": 1019.47,
        "humidity": 59,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 12.77,
        "deg": 199.501
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2017-05-01 09:00:00"
    },
    {
      "dt": 1493640000,
      "main": {
        "temp": 73.92,
        "temp_min": 73.92,
        "temp_max": 73.92,
        "pressure": 1019.33,
        "sea_level": 1025.75,
        "grnd_level": 1019.33,
        "humidity": 63,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": {
        "all": 68
      },
      "wind": {
